name: Build ZMK firmware
# on: [push, pull_request, workflow_dispatch]
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
